"use client";

import DashboardV1 from "@/components/CUSTOM/Dashboard-V1";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isOpen, setIsOpen] = useState(false);
  console.log(`THIS IS   isOpen:`, isOpen);
  return (
    <html lang="en">
      <body className={cn("", inter.className)}>
        <div className="flex ">
          <DashboardV1
            isOpen={isOpen}
            onClickOverlayClose={() => {
              setIsOpen(false);
            }}
          />
          <main className="flex-1">
            <Header setIsOpen={setIsOpen} />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
